travis:
  secure:
    BINSTAR_TOKEN: F3y3fGWRzDJLQ8T47vVwP17AFqFQHnIqR0MbnTyqYPlBWKhMP4Fo4QI7bkTiGAZnB39OfrUJf3uOofuF7HlWimiQQfqFJxeAJk8f6uoK6yBhTbGjVmFqU6o02SVV2CtF6e4uggHqrKqkY4HCJTrki6JR/FAwZdgBBeVULp05bvbwe3hXyixsyXXgZpZT0zHFamvXAeJXljk8aTWkx/EjqBW7+RGsUtWYq01fgUql8ljEsuQEGzefCXMsC0yo3UtWLk22kaYEKZp47RR2ob8MRc3TqPoPjzjoltRORQQKwcaMrlb8fu5I4UbsZPlIBEPvteWPQjpqy5Q0/AfsTPQ+/uTdKHZBYdEi567rs2M91DoVbdy42gtpD/VTIf0TWJ84+YulOm1d68eSJzHPoReAoGCfMJwqJfatRm7ZYpPVQl3JJXMAXSpC4AOV8Qy1zz8EQO86Hl8W9HboQLt2midRA6JFuOWA9B+s17KHuhBQWCAyxvHf76Ch7EHYA/t4xCRwLPTUGXg+lGUjB6x8iM3ELL5W4NAOzPw1vLT5N63SitPCu1+teDN8IkH8fMi93rQ8hdkY7J6Ifl7cwhqZieq90Nt6sPFh1AqJYlbT+tcLkNthGEqY/X2vODmOKurvXpghiQ/ePA3v6WIkgFNCU7W6DkBMnHZrtD5aqfOtyFGjvcA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
osx_provider: circle
